### ISSUE TITLE
Design Principles + SOLID

### ISSUE THREAD

**Issue by Christabellet** [rawsashimi1604/ICT2106_P2_Project_M2#137]
Start Date: 29/03/2023
End Date: 30/03/2023

### Preconditions:
- None

### Definition of done:
- [x] S of SOLID principle done
- [x] D of SOLID principle done
- [x] Factory design pattern done
- [x] Builder design pattern done
- [x] Proxy design pattern done

**Comment by jianweiiii** [comment]
In D1, our Notification classes directly depended on concrete classes, causing tight coupling between modules. This violated the Dependency Inversion Principle, thus making it difficult to modify, test, and maintain our codebase.

To adhere to the Dependency Inversion Principle, we made the following changes in D2. Firstly We created interfaces to represent the abstractions for our Notification classes. These interfaces defined the contract or the methods that the concrete classes implementing the interface should provide. This way, high-level modules can depend on these abstractions rather than the concrete Notification classes, promoting loose coupling. 

Then we also implemented Dependency injection (DI) a technique that allows the injection of dependencies (such as interface implementations) into a class rather than the class creating the dependency itself. In our project, we used the .NET Core framework built-in DI container to manage and inject these dependencies. By injecting the appropriate interface implementations into services and controllers, we further decoupled our modules, making them more independent and easier to test

To further adhere to the Dependency Inversion Principle and enhance the decoupling of our modules, we used proxy patterns and repositories in our design which we will discuss further below in our report at [5.3 Design Pattern #3 (Proxy)](https://docs.google.com/document/d/1ZMP2uF3h18ITik7IX1H14V0zSiLDV0wh/edit#heading=h.9ns1wcq7rl3x).  Repositories, on the other hand, act as an abstraction layer between the data access layer and the business logic layer. By using these patterns, we further separated the concerns in our system and ensured that modules depend on abstractions rather than concrete implementations.

**Comment by junweilam** [comment]
![Image](https://user-images.githubusercontent.com/91267859/228890915-651e14da-e56a-4e59-93d5-cef23c5c2926.png)




![Image](https://user-images.githubusercontent.com/91267859/228890982-b3197cc9-79d3-4f34-a0d5-6076305adacb.png)

**Comment by rawsashimi1604** [comment]
![Image](https://user-images.githubusercontent.com/75880261/228893385-5adac8aa-7c92-42f6-9e12-a75713718ef7.png)



![Image](https://user-images.githubusercontent.com/75880261/228893448-76ff3470-c20a-4202-af2e-237a9ff1f7cb.png)



![Image](https://user-images.githubusercontent.com/75880261/228893483-c1e0fbf5-fa5c-416c-8b30-bb43ee1d2f4b.png)

Factory done
